FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Pamaxie.Database.Api/Pamaxie.Database.Api.csproj", "Pamaxie.Database.Api/"]
COPY ["Pamaxie.Database.Design/Pamaxie.Database.Design.csproj", "Pamaxie.Database.Design/"]
COPY ["Pamaxie.Database.Native/Pamaxie.Database.Native.csproj", "Pamaxie.Database.Native/"]
COPY ["Pamaxie.Authentication/Pamaxie.Authentication.csproj", "Pamaxie.Authentication/"]
RUN dotnet restore "Pamaxie.Database.Api/Pamaxie.Database.Api.csproj"
COPY . .
WORKDIR "/src/Pamaxie.Database.Api"
RUN dotnet build "Pamaxie.Database.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Pamaxie.Database.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV DOTNET_RUNNING_IN_CONTAINER=true
ENTRYPOINT ["dotnet", "Pamaxie.Database.Api.dll"]
